version: '3.8'
services:
  rainy:
    build: ./
    image: rainy
    container_name: rainy
    restart: always
    command: [ 'node', 'dist/main.js' ]
    networks:
      - rainy-network
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass $PASSWORD --appendonly yes
    volumes:
      - ./volumes/redis:/data:rw,z
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - rainy-network

# Docker Networks
networks:
  # All container connect in a network
  rainy-network:
    driver: bridge
